# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'AnApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnApp
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'FirebaseDatabase'
  pod 'IQKeyboardManagerSwift', '6.5.0'
  pod 'CLTypingLabel'
  pod 'Mapbox-iOS-SDK', '~> 4.9'
end
